# An optional file docutils.conf can be added to the configuration
# directory to adjust Docutils configuration if not otherwise overridden
# or set by Sphinx.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.


# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

import sphinx
import sphinx_revealjs
import sphinx_rtd_theme
import semver
import git
import sys
import os

logcfg = sphinx.util.logging.getLogger(__name__)
on_rtd = os.environ.get('READTHEDOCS', None) == 'True'
on_windows = sys.platform.startswith('win')

if "DOCSRC" not in os.environ:
    DOCSRC = os.path.abspath(os.getcwd())
else:
    DOCSRC = os.path.abspath(os.environ["DOCSRC"])


# -- Project information -----------------------------------------------------

docstat = 'preliminary (:emphasis:`some mature, much in progress`)'
docnumb = 'LPN-QMS-SHOW-00000'
doctype = 'Learning'
project = 'Yocto'
author = 'Li-Pro.Net — Documentation'
publisher = 'Li-Pro.Net'
contactaddr = 'Jena, Germany'
contactemail = 'info@li-pro.net'
copyright = '2018‒2021 ' + publisher + ' and individual contributors.'
category = 'Presentation'
about = doctype + ' ' + project + '.'
keywords = docnumb + ',' + doctype + ',' + project + ',Bitbake'

# Define basic strings that will be used in the dictionary of external sites.
ghp_base = 'https://lipro.github.io/'
ghp_slug = 'lpn-show-learning-yocto'
ghp_name = 'Li-Pro.Net ' + doctype + ' ' + project

if on_rtd:
    git_describe = ('--dirty=+RTDS', '--broken=+broken')
else:
    git_describe = ('--dirty=+dirty', '--broken=+broken')

try:
    repo = git.Repo(search_parent_directories=True)
    semv = semver.VersionInfo.parse(repo.git.describe(git_describe))
    sha1 = repo.head.object.hexsha.lower()
except:
    # fallback to unknown version / release
    semv = semver.VersionInfo.parse('0.0.0-invalid+unknown')
    sha1 = '0000000000000000000000000000000000000000'

# The short SHA1 for identification
identify = repo.git.rev_parse(sha1, short=8)

# The short X.Y.Z version
version = str(semv.finalize_version())
genvers = str(semv.major)

# The full version, including alpha/beta/rc tags
release = str(semv)

# Combined document title and subtitle
# title = project + ' ' + version
title = project
subtitle = doctype

# Single target file names
namespace = 'net.li-pro.doc.presentation.yocto.learning.' + version + '.'
basename = 'lpn-doc-learning-yocto'

logcfg.info(project + ' ' + release, color='yellow')


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-needs_sphinx
#
needs_sphinx = '3.4.3'
build_sphinx = sphinx.__version__

# This value can be a dictionary specifying version requirements for
# extensions in 'extensions'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-needs_extensions
#
needs_extensions = {
#   'sphinx.ext.autodoc':                               needs_sphinx,
#   'sphinx.ext.autosummary':                           needs_sphinx,
    'sphinx.ext.autosectionlabel':                      needs_sphinx,
    'sphinx.ext.doctest':                               needs_sphinx,
    'sphinx.ext.coverage':                              needs_sphinx,
    'sphinx.ext.todo':                                  needs_sphinx,
    'sphinx.ext.ifconfig':                              needs_sphinx,
    'sphinx.ext.intersphinx':                           needs_sphinx,
    'sphinx.ext.extlinks':                              needs_sphinx,
#   'sphinx.ext.viewcode':                              needs_sphinx,
#   'sphinx.ext.linkcode':                              needs_sphinx,
#   'sphinx.ext.imgmath':                               needs_sphinx,
    'sphinx.ext.mathjax':                               needs_sphinx,
#   'sphinx.ext.jsmath':                                needs_sphinx,
#   'sphinx.ext.graphviz':                              needs_sphinx,
#   'sphinx.ext.imgconverter':                          needs_sphinx,
#   'sphinx.ext.inheritance_diagram':                   needs_sphinx,
#   'sphinx_rtd_theme':                                 '0.5.1',
    'sphinx_revealjs':                                  '1.0.0',
#   'sphinxcontrib.inkscapeconverter':                  '1.1.1',
    'sphinxcontrib.rsvgconverter':                      '1.1.1',
#   'sphinxcontrib.cairosvgconverter':                  '1.1.1',
#   'sphinxcontrib.bibtex':                             '2.1.4',
    'sphinxcontrib.spelling':                           '7.1.0',
    'linuxdoc.rstFlatTable':                            '20210110',
}

extensions = [
#   'sphinx.ext.autodoc',
#   'sphinx.ext.autosummary',
    'sphinx.ext.autosectionlabel',
    'sphinx.ext.doctest',
    'sphinx.ext.coverage',
    'sphinx.ext.todo',
    'sphinx.ext.ifconfig',
    'sphinx.ext.intersphinx',
    'sphinx.ext.extlinks',
#   'sphinx.ext.viewcode',
#   'sphinx.ext.linkcode',
#   'sphinx.ext.imgmath',
    'sphinx.ext.mathjax',
#   'sphinx.ext.jsmath',
#   'sphinx.ext.graphviz',
#   'sphinx.ext.imgconverter',
#   'sphinx.ext.inheritance_diagram',
    'sphinx_rtd_theme',
    'sphinx_revealjs',
#   'sphinxcontrib.inkscapeconverter',
    'sphinxcontrib.rsvgconverter',
#   'sphinxcontrib.cairosvgconverter',
    'sphinxcontrib.bibtex',
    'sphinxcontrib.spelling',
    'linuxdoc.rstFlatTable',
]


# -- Specific configuration --------------------------------------------------

path_extra = os.path.join(DOCSRC, '_extra')
logcfg.info('EXTRAS     path is: "{}"'.format(path_extra), color='green')

path_images = os.path.join(DOCSRC, '_images')
logcfg.info('IMAGES     path is: "{}"'.format(path_images), color='green')

path_templates = os.path.join(DOCSRC, '_templates')
logcfg.info('TEMPLATE   path is: "{}"'.format(path_templates), color='green')

path_html_templates = os.path.join(path_templates, 'html')
logcfg.info('-- HTML    path is: "{}"'.format(path_html_templates), color='green')

path_latex_templates = os.path.join(path_templates, 'latex')
logcfg.info('-- LaTeX   path is: "{}"'.format(path_latex_templates), color='green')

path_dictionaries = os.path.join(path_templates, 'dicts')
logcfg.info('DICTS      path is: "{}"'.format(path_dictionaries), color='green')

path_static = os.path.join(DOCSRC, '_static')
logcfg.info('STATIC     path is: "{}"'.format(path_static), color='green')

path_dejavu = os.path.join(path_static, 'html', 'fonts', 'DejaVu')
logcfg.info('DejaVu     path is: "{}"'.format(path_dejavu), color='green')

path_wenquanyi = os.path.join(path_static, 'html', 'fonts', 'WenQuanYi')
logcfg.info('WenQuanYi  path is: "{}"'.format(path_wenquanyi), color='green')

path_bibtex = os.path.join(DOCSRC, '_bibliography')
logcfg.info('BibTeX     path is: "{}"'.format(path_bibtex), color='green')


# -- Sphinx Basic Configuration ----------------------------------------------

# Add any paths that contain templates here, relative to this directory.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-templates_path
#
templates_path = [
    '{}'.format(path_html_templates),
    '{}'.format(path_latex_templates),
]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-internationalization
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-language
#
language = 'en'

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-source_suffix
#
# source_suffix = ['.rst', '.md']
source_suffix = {
    '.rst': 'restructuredtext',
}

# The master toctree document.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-master_doc
#
master_doc = 'index'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-exclude_patterns
#
exclude_patterns = [
    '**/.gitkeep',
]

# A string of reStructuredText that will be included at the beginning of every
# source file that is read.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-rst_prolog
#
rst_prolog = u'''
.. include:: /{docsrc}/docroles.rsti
.. include:: /{docsrc}/docmeta.rsti
.. |CREDITS| replace:: :download:`CREDITS </CREDITS>`
.. |LICENSE| replace:: :download:`LICENSE </LICENSE>`
.. |docsrc| replace:: {docsrc}
.. |docstat| replace:: {docstat}
.. |docnumb| replace:: {docnumb}
.. |genvers| replace:: {genvers}
.. |identify| replace:: {identify}
.. |title| replace:: {title}
.. |subtitle| replace:: {subtitle}
.. |publisher| replace:: {publisher}
.. |copyright| replace:: {copyright}
.. |project| replace:: {project}
.. |author| replace:: {author}
.. |about| replace:: {about}
.. |contactaddr| replace:: {contactaddr}
.. |contactemail| replace:: {contactemail}
.. |ghp_name| replace:: {ghp_name}
.. |ghp_name_e| replace:: :emphasis:`{ghp_name}`
.. |ghp_name_s| replace:: :strong:`{ghp_name}`
.. meta::
   :producer: {producer}
   :creator: {creator}
   :publisher: {publisher}
   :subject: {subject}
   :keywords: {keywords}
   :author: {author}
   :copyright: {copyright}
   :docstat: {docstat}
   :docnumb: {docnumb}
   :project: {project}
   :title: {title}
   :subtitle: {subtitle}
   :version: {version}
   :release: {release}
   :identify: {identify}
'''.format(
    docsrc = DOCSRC,
    docstat = docstat,
    docnumb = docnumb,
    genvers = genvers,
    version = version,
    identify = identify,
    release = release,
    title = title,
    subtitle = subtitle,
    copyright = copyright,
    project = project,
    author = author,
    about = about,
    contactaddr = contactaddr,
    contactemail = contactemail,
    producer = 'Sphinx ' + build_sphinx,
    creator = 'Sphinx ' + build_sphinx,
    publisher = publisher,
    subject = about,
    keywords = keywords,
    ghp_name = ghp_name,
)

# A string of reStructuredText that will be included at the end of every source
# file that is read. This is the right place to add substitutions that should be
# available in every file.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-rst_epilog
#
rst_epilog = '''
.. include:: /{docsrc}/docterms.rsti
.. include:: /{docsrc}/docextlnk.rsti
.. include:: /{docsrc}/docunicode.rsti
'''.format(
    docsrc = DOCSRC,
)

# This change will allow us to use bare back-tick notation to let
# Sphinx hunt for a reference, starting with normal "document"
# references such as :ref:, but also including :c: and :cpp: domains
# (potentially) helping with API (doxygen) references simply by using
# `name`
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-primary_domain
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-default_role
#
#primary_domain = 'cpp'
default_role = 'any'

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-show_authors
#
#show_authors = False
show_authors = True

# The name of the Pygments (syntax highlighting) style to use.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-pygments_style
#
pygments_style = 'sphinx'

# If true, figures, tables and code-blocks are automatically numbered if they
# have a caption. At same time, the numref role is enabled. For now, it works
# only with the HTML builder and LaTeX builder. Default is False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig
#
numfig = True

# A dictionary mapping 'figure', 'table' and 'code-block' to strings that are
# used for format of figure numbers. Default is to use 'Fig. %s' for 'figure',
# 'Table %s' for 'table' and 'Listing %s' for 'code-block'.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig_format
#
numfig_format = {
    'code-block': 'Listing %s',
    'sections': 'Section %s',
    'figure': 'Figure %s',
    'table': 'Table %s',
}

# The scope of figure numbers, that is, the numfig feature numbers figures in
# which scope. 0 means “whole document”. 1 means “in a section”. Sphinx numbers
# like x.1, x.2, x.3... 2 means “in a subsection”. Sphinx numbers like x.x.1,
# x.x.2, x.x.3..., and so on. Default is 1.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-numfig_secnum_depth
#
numfig_secnum_depth = 1

# Set this option to True if you want all displayed math to be numbered.
# The default is False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_number_all
#
math_number_all = True

# A string used for formatting the labels of references to equations. The
# {number} place-holder stands for the equation number. Example: 'Eq.{number}'
# gets rendered as, for example, Eq.10.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-math_eqref_format
#
math_eqref_format = 'Equastion {number}'

# A User-Agent of Sphinx. It is used for a header on HTTP access
# (ex. linkcheck, intersphinx and so on).
# Default is "Sphinx/X.Y.Z requests/X.Y.Z python/X.Y.Z".
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-user_agent
#
user_agent = 'Mozilla/5.0 AppleWebKit/537.36 Chrome/87.0.4280.88 Safari/537.36'

# If true, Sphinx verifies server certifications. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-tls_verify
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-tls_cacerts
#
# tls_verify = True
# tls_verify = False

# some configuration for linkcheck builder
#   noticed that we're getting false-positive link errors on different server,
#   I suspect because it's taking too long for the server to respond so bump
#   up the timeout (default=5) and turn off anchor checks (so only a HEAD
#   request is done - much faster). Leave the ignore commented in case we want
#   to remove different server link checks later...

#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_ignore
#
#linkcheck_ignore = ['http://localhost:\d+/']
linkcheck_ignore = [
    'http://localhost:\d+/',
]

# The number of times the linkcheck builder will attempt to check a URL before
# declaring it broken. Defaults to 1 attempt.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_retries
#
# linkcheck_retries = 1
linkcheck_retries = 5

# A timeout value, in seconds, for the linkcheck builder. The default is to use
# Python’s global socket timeout.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_timeout
#
linkcheck_timeout = 60

# The number of worker threads to use when checking links.
# Default is 5 threads.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_workers
#
# linkcheck_workers = 5
linkcheck_workers = 10

# True or false, whether to check the validity of #anchors in links.
# Since this requires downloading the whole document, it’s considerably
# slower when enabled. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_anchors
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-linkcheck_anchors_ignore
#
#linkcheck_anchors = True
linkcheck_anchors = False


# -- Options for sphinx.ext.autosectionlabel -- Allow reference sections -----
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/autosectionlabel.html
#

# Internally, this extension generates the labels for each section. If same
# section names are used in whole of document, any one is used for a target
# by default. The autosectionlabel_prefix_document configuration variable
# can be used to make headings which appear multiple times but in different
# documents unique.

# True to prefix each section label with the name of the document it is in,
# followed by a colon. For example, index:Introduction for a section called
# Introduction that appears in document index.rst. Useful for avoiding
# ambiguity when the same section heading appears in different documents.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/autosectionlabel.html#confval-autosectionlabel_prefix_document
#
autosectionlabel_prefix_document = True


# -- Options for sphinx.ext.todo -- Support for todo items -------------------
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/todo.html
#

# If this is True, `todo` and `todoList` produce output, else they produce
# nothing. The default is False.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/todo.html#confval-todo_include_todos
#
todo_include_todos = True


# -- Options for sphinx.ext.ifconfig -- Include content based on configuration
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/ifconfig.html
#

# This extension can generate automatic links to the documentation
# of objects in other projects. Usage is simple: whenever Sphinx
# encounters a cross-reference that has no matching target in the
# current documentation set, it looks for targets in the documentation
# sets configured in intersphinx_mapping.

# This config value contains the locations and names of other projects
# that should be linked to in this documentation.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/intersphinx.html#confval-intersphinx_mapping
#
# Example configuration for intersphinx: refer to the Python standard library.
# intersphinx_mapping = {'https://docs.python.org/3/': None}

# if on_rtd:
#     intersphinx_mapping = {
#         'sphinx': ('/Users/rexut/checkouts/sphinx/doc/_build/html/', None),
#     }
# else:
intersphinx_mapping = {
    #
    # Standard reference to this docs, with local objects.inv
    #

    # python -m sphinx.ext.intersphinx 'docs/_build/html/objects.inv'
    # '': ('{}/html/'.format(DOCBLD), None),

    #
    # Standard reference to web docs, with web objects.inv
    #

    # python -m sphinx.ext.intersphinx 'https://docs.python.org/3/objects.inv'
    'pydocs': ('https://docs.python.org/3/', None),

    # python -m sphinx.ext.intersphinx 'https://devguide.python.org/objects.inv'
    'pydevguide': ('https://devguide.python.org/', None),

    # python -m sphinx.ext.intersphinx 'https://www.sphinx-doc.org/en/3.x/objects.inv'
    'sphinx': ('https://www.sphinx-doc.org/en/3.x/', None),

    # python -m sphinx.ext.intersphinx 'https://rest-sphinx-memo.readthedocs.io/en/stable/objects.inv'
    'spxmemo': ('https://rest-sphinx-memo.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinxcontrib-spelling.readthedocs.io/en/stable/objects.inv'
    'scspelling': ('https://sphinxcontrib-spelling.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://sphinxcontrib-bibtex.readthedocs.io/en/stable/objects.inv'
    'scbibtex': ('https://sphinxcontrib-bibtex.readthedocs.io/en/stable/', None),

    # python -m sphinx.ext.intersphinx 'https://return42.github.io/linuxdoc/objects.inv'
    'lxdoc': ('https://return42.github.io/linuxdoc/', None),

    # python -m sphinx.ext.intersphinx 'https://docs.yoctoproject.org/objects.inv'
    'ypdoc': ('https://docs.yoctoproject.org/', None),

    # python -m sphinx.ext.intersphinx 'https://docs.yoctoproject.org/bitbake/objects.inv'
    'bbdoc': ('https://docs.yoctoproject.org/bitbake/', None),

    #
    # Drawing the Docutils objects.inv from a RTD server,
    # but referring to the 0.16 web docs
    # Idea comes from https://sphobjinv.readthedocs.io/en/latest/
    #

    # python -m sphinx.ext.intersphinx 'https://docutils.readthedocs.io/en/sphinx-docs/objects.inv'
#   'docutils': ('https://docutils.sourceforge.io/docs/',
#                'https://docutils.readthedocs.io/en/sphinx-docs/objects.inv'),
}

# -- Options for sphinx.ext.extlinks -- Markup to shorten external links -----
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/extlinks.html
#

# This extension is meant to help with the common pattern of having many
# external links that point to URLs on one and the same site, e.g. links
# to bug trackers, version control web interfaces, or simply subpages in
# other websites. It does so by providing aliases to base URLs, so that
# you only need to give the subpage name when creating a link.

# This config value must be a dictionary of external sites, mapping unique
# short alias names to a base URL and a prefix.
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/extlinks.html#confval-extlinks
#
extlinks = {
    'wikide':       ('https://de.wikipedia.org/wiki/%s', 'German Wikipedia: '),
    'wikien':       ('https://en.wikipedia.org/wiki/%s', 'English Wikipedia: '),
    'wikioe':       ('https://www.openembedded.org/wiki/%s', 'OpenEmbedded Wikipedia: '),
    'oelayer':      ('https://layers.openembedded.org/%s', 'OpenEmbedded Layer Index: '),
    'wikiyp':       ('https://wiki.yoctoproject.org/wiki/%s', 'Yocto Project Wiki: '),
    'homeyp':       ('https://www.yoctoproject.org/%s', 'Yocto Project Home: '),
    'lpn.ghp.dir': (
        ghp_base + ghp_slug + '/%s',
        ghp_name + ': '
    ),
    'lpn.ghp.file': (
        ghp_base + ghp_slug + '/' + basename + '.%s',
        ghp_name + ': '
    ),
}


# -- Options for sphinx.ext.viewcode -- Add links to highlighted source code -
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/viewcode.html
#


# -- Options for sphinx.ext.linkcode -- Add external links to source code ----
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/linkcode.html
#


# -- Options for sphinx.ext.*math* -- Math support for HTML outputs in Sphinx
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/math.html
#
#    sphinx.ext.imgmath -- Render math as images
#    sphinx.ext.mathjax -- Render math via JavaScript (prefered)
#    sphinx.ext.jsmath  -- Render math via JavaScript
#


# -- Options for sphinx.ext.graphviz -- Add Graphviz graphs ------------------
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/graphviz.html
#


# -- Options for sphinx.ext.imgconverter -- Converter using Imagemagick ------
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/inheritance.html
#
# Note: Imagemagick rasterizes a SVG image on conversion. As a result, the
#       image becomes not scalable. To avoid that, please use other image
#       converters like sphinxcontrib-svg2pdfconverter (which uses Inkscape
#       or rsvg-convert).
#
# https://github.com/missinglinkelectronics/sphinxcontrib-svg2pdfconverter
#


# -- Options for sphinx.ext.inheritance_diagram -- Include inheritance diagrams
#
# https://www.sphinx-doc.org/en/3.x/usage/extensions/inheritance.html
#


# -- Options for sphinxcontrib-svg2pdfconverter -- Convert SVG images to PDF -
#
# https://pypi.org/project/sphinxcontrib-svg2pdfconverter/
#
#    sphinxcontrib.inkscapeconverter -- either Inkscape,
#    sphinxcontrib.rsvgconverter     -- rsvg-convert from libRSVG or
#    sphinxcontrib.cairosvgconverter -- CairoSVG
#

# Path to Inkscape binary. By default, this is:
#inkscape_converter_bin = 'inkscape'

# Additional command-line arguments for Inkscape, as a list.
# By default, this is:
#inkscape_converter_args = ['--export-area-drawing']

# Path to RSVG converter binary. By default, this is:
#rsvg_converter_bin = 'rsvg-convert'

# Additional command-line arguments for the RSVG converter, as a list.
# By default, this is the emtpy list:
#rsvg_converter_args = []


# -- Options for sphinxcontrib.bibtex -- Insert BibTeX citations -------------
#
# https://sphinxcontrib-bibtex.readthedocs.io/en/2.1.4/
# https://sphinxcontrib-bibtex.readthedocs.io/en/2.1.4/usage.html#configuration
#

# This setting specifies all bib files used throughout the project, relative to
# the source folder. This configuration is new and mandatory (since 2.0.0).
bibtex_bibfiles = [
    '{}/sphinx.bib'.format(path_bibtex),
    '{}/python.bib'.format(path_bibtex),
    '{}/yocto.bib'.format(path_bibtex),
]

# Set the encoding of the bibliography files. If no encoding is specified,
# 'utf-8-sig' is assumed.
# bibtex_encoding = 'latin'


# -- Options for sphinxcontrib.spelling -- Spelling Checker ------------------
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/
#

# String specifying the language, as understood by PyEnchant and enchant.
# Defaults to en_US for US English.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#input-options
#
# spelling_lang = 'en_US'

# String specifying a file containing a list of words known to be spelled
# correctly but that do not appear in the language dictionary selected
# by spelling_lang. The file should contain one word per line. Refer to
# the PyEnchant tutorial for details.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#input-options
#
# spelling_word_list_filename = 'spelling_wordlist.txt'
spelling_word_list_filename = [
    '{}/american-english-huge'.format(path_dictionaries),
    '{}/ngerman'.format(path_dictionaries),
    '{}/missing'.format(path_dictionaries),
    '{}/companies'.format(path_dictionaries),
    '{}/electronics'.format(path_dictionaries),
    '{}/proper-nouns'.format(path_dictionaries),
]

# A list of glob-style patterns that should be ignored when checking
# spelling. They are matched against the source file names relative
# to the source directory, using slashes as directory separators on
# all platforms. See Sphinx's exclude_patterns option for more details
# on glob-style patterns.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#input-options
#
spelling_exclude_patterns = [
    'doc*.rsti',
    'index*.rst',
    'bibliography.rst',
]

# Boolean controlling whether suggestions for misspelled words are printed.
# Defaults to False.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#output-options
#
spelling_show_suggestions = True

# Boolean controlling whether the contents of the line containing each
# misspelled word is printed, for more context about the location of
# each word. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#output-options
#
# spelling_show_whole_line = True

# Boolean controlling whether words that look like package names from PyPI
# are treated as spelled properly. When True, the current list of package
# names is downloaded at the start of the build and used to extend the list
# of known words in the dictionary. Defaults to False.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_pypi_package_names = False

# Boolean controlling whether words that follow the CamelCase conventions
# used for page names in wikis should be treated as spelled properly.
# Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_wiki_words = True

# Boolean controlling treatment of words that appear in all capital letters,
# or all capital letters followed by a lower case s. When True, acronyms are
# assumed to be spelled properly. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_acronyms = True

# Boolean controlling whether names built in to Python should be treated as
# spelled properly. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_python_builtins = True

# Boolean controlling whether words that are names of modules found on
# sys.path are treated as spelled properly. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_importable_modules = True

# Boolean controlling treatment of contributor names extracted from the git
# history as spelled correctly, making it easier to refer to the names in
# acknowledgments. Defaults to True.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_ignore_contributor_names = True

# List of filter classes to be added to the tokenizer that produces words
# to be checked. The classes should be derived from enchant.tokenize.Filter.
# Refer to the PyEnchant tutorial for examples.
#
# https://sphinxcontrib-spelling.readthedocs.io/en/stable/customize.html#word-filters
#
# spelling_filters = []


# -- Options for linuxdoc.rstFlatTable -- Create flat table content ----------
#
# https://return42.github.io/linuxdoc/
# https://github.com/return42/linuxdoc
#


# -- Options for LaTeX output ------------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/latex.html
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-latex-output
#
# https://www.sphinx-doc.org/en/master/latex.html
# https://blog.michael.franzl.name/2014/12/10/xelatex-unicode-font-fallback-unsupported-characters/
# https://tex.stackexchange.com/questions/344100/
# https://tex.stackexchange.com/questions/323575/

# TODO: evaluate possible admonitionbox override, see:
#       http://stackoverflow.com/a/13661732
# Left aligne captions: http://tex.stackexchange.com/questions/136688/how-to-align-caption-with-table

latex_title = u'{title}\\\\{subtitle}'.format(
    title = title,
    subtitle = subtitle,
)

latex_author = u'{publisher}\\\\{author}'.format(
    publisher = publisher,
    author = author,
)

latex_releasename = u'Document Number: \sphinxstylestrong{{{docnumb}}}\\\\ Revision:'.format(
    docnumb = docnumb,
)

f = open('{}/extrapackages.tex'.format(path_latex_templates), 'r+')
latex_custom_extrapackages = f.read()

f = open('{}/passoptstopackages.tex.in'.format(path_latex_templates), 'r+')
latex_custom_passoptionstopackages = f.read().format (
    producer = 'Sphinx ' + build_sphinx,
    creator = 'Sphinx ' + build_sphinx,
    publisher = publisher,
    subject = about + ' Release: ' + release + ' (' + identify + ')',
    keywords = keywords,
)

f = open('{}/preamble.tex.in'.format(path_latex_templates), 'r+')
latex_custom_preamble = f.read().format (
    docnumb = docnumb,
    identify = identify,
    publisher = publisher,
    contactaddr = contactaddr,
    contactemail = contactemail,
)

if on_windows:
    latex_custom_fontpkg = ''
else:
    f = open('{}/fontpkg.tex.in'.format(path_latex_templates), 'r+')
    latex_custom_fontpkg = f.read().format (
        dejavu = path_dejavu + '/',
        wenquanyi = path_wenquanyi + '/',
    )

f = open('{}/utf8extra.tex'.format(path_latex_templates), 'r+')
latex_custom_utf8extra = f.read()

# The LaTeX engine to build the docs. The setting can have the
# following values:
#   'pdflatex' – PDFLaTeX (default, limited Unicode characters support)
#   'xelatex' – XeLaTeX
#   'lualatex' – LuaLaTeX
#   'platex' – pLaTeX (default if language is 'ja')
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_engine
#
latex_engine = 'xelatex'

# A dictionary that contains LaTeX snippets overriding those Sphinx
# usually puts into the generated .tex files.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_elements
# http://www.sphinx-doc.org/en/3.x/latex.html#latex-elements-confval
# http://www.sphinx-doc.org/en/3.x/latex.html
#
latex_elements = {
    #
    # Keys that you may want to override include:
    #
    'extraclassoptions': 'table',

    # Paper size option of the document class ('letterpaper' or 'a4paper'),
    # default 'letterpaper'.
    'papersize': 'a4paper',

    # Point size option of the document class ('10pt', '11pt' or '12pt'),
    # default '10pt'.
    'pointsize': '10pt',

    # "babel" package inclusion, default r'\usepackage{babel}'.
    'babel': r'\usepackage[english]{babel}',

    # "geometry" package inclusion, default r'\usepackage{geometry}'.
    # note: 'total={w,h}' depends hard on 'a4paper', see above.
    'geometry': r'\usepackage[total={170mm,257mm},left=25mm,right=15mm,top=20mm,headsep=10mm]{geometry}',
#   'geometry': r'\usepackage[headsep=1.0cm,left=2.5cm,right=1.5cm]{geometry}',

    # Font package inclusion, default r'\usepackage{times}' (which uses Times
    # and Helvetica). You can set this to '' to use the Computer Modern fonts.
    # Defaults to '' when the language uses the Cyrillic script.
    # For xelatex it defaults to: '''\setmainfont{FreeSerif}[..]
    # \setsansfont{FreeSans}[..]\setmonofont{FreeMono}[..]'''
    'fontpkg': latex_custom_fontpkg,

    # Inclusion of the "fncychap" package (which makes fancy chapter titles),
    # default r'\usepackage[Bjarne]{fncychap}' for English documentation,
    # r'\usepackage[Sonny]{fncychap}' for internationalized docs (because the
    # "Bjarne" style uses numbers spelled out in English). Other "fncychap"
    # styles you can try include "Lenny", "Glenn", "Conny" and "Rejne". You can
    # also set this to '' to disable fncychap.
#   'fncychap': r'\usepackage[Sonny]{fncychap}',
#   'fncychap': r'\usepackage[Lenny]{fncychap}',
#   'fncychap': r'\usepackage[Glenn]{fncychap}',
#   'fncychap': r'\usepackage[Conny]{fncychap}',
#   'fncychap': r'\usepackage[Rejne]{fncychap}',
#   'fncychap': r'\usepackage[Bjarne]{fncychap}',
    'fncychap': r'\usepackage[Bjornstrup]{fncychap}',

    # Additional package inclusion, default empty.
    'extrapackages': latex_custom_extrapackages,

    # "PassOptionsToPackage" call, default empty.
    'passoptionstopackages': latex_custom_passoptionstopackages,

    # Additional preamble content, default empty.
    'preamble': latex_custom_preamble,

    # Latex figure (float) alignment, default 'htbp' (here, top, bottom, page).
    # Whenever an image doesn't fit into the current page, it will be 'floated'
    # into the next page but may be preceded by any other text. If you don't
    # like this behavior, use 'H' which will disable floating and position
    # figures strictly in the order they appear in the source.
    'figure_align': 'H',

    # Latex number figure format, default empty.
#   'numfig_format': '',

    #
    # Keys that don’t need be overridden unless in special cases are:
    #

    # "inputenc" package inclusion, defaults to r'\usepackage[utf8]{inputenc}'
    # when using pdflatex. Otherwise unset.
#   'inputenc': r'\usepackage[utf8]{inputenc}',

    # Unicode character declaration, for xelatex defaults to:
    # \catcode`^^^^00a0\active\protected\def^^^^00a0{\leavevmode\nobreak\ }
    'utf8extra': latex_custom_utf8extra,

    # "cmap" package inclusion, default r'\usepackage{cmap}'.
#   'cmappkg': r'\usepackage{cmap}',

    # "fontenc" package inclusion, default r'\usepackage[T1]{fontenc}' and
    # r'\usepackage{fontspec}\defaultfontfeatures[\rmfamily,\sffamily,\ttfamily]{}'
    # in case of xelatex for non-mandarin languages.
#   'fontenc': r'\usepackage[T1]{fontenc}',

    # "amsmath" package inclusion, default r'\usepackage{amsmath,amssymb,amstext}'.
#   'amsmath': r'\usepackage{amsmath,amssymb,amstext}',

    # Value that prefixes 'release' element on title page, default 'Release'.
    'releasename': latex_releasename,

    # "makeindex" call, default r'\makeindex'. Override if you want to
    # generate a differently-styled index page.
#   'makeindex': r'\makeindex',

    # "maketitle" call, default r'\sphinxmaketitle'. Override if you want to
    # generate a differently-styled title page.
#   'maketitle': r'\sphinxmaketitle',

    # "tableofcontents" call, default r'\sphinxtableofcontents'. Override if
    # you want to generate a different table of contents or put content between
    # the title page and the TOC.
#   'tableofcontents': r'\sphinxtableofcontents',

    # "printindex" call, the last thing in the file, default r'\printindex'.
    # Override if you want to generate the index differently or append some
    # content after the index.
    'printindex': r'\footnotesize\raggedright\printindex',

    # Commands used to display transitions, default r'\n\n\bigskip\hrule{}\bigskip\n\n'.
    # Override if you want to display transitions differently.
#   'transition': r'\n\n\bigskip\hrule{}\bigskip\n\n',

    #
    # Keys that are set by other options and therefore should not be
    # overridden are: 'docclass' 'classoptions' 'extraclassoptions'
    #                 'contentsname' 'title' 'date' 'release'
    #                 'author' 'logo' 'makeindex' 'shorthandoff'
    #                 'tocdepth' 'pageautorefname'
    #

    # Get rid of evenly numbered empty pages (default book style)
#   'classoptions': ',openany,oneside',
    'classoptions': ',twoside',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_documents
#
latex_documents = [
    (master_doc, basename + '.tex', latex_title, latex_author, 'manual'),
]
latex_docclass = {'manual': 'book'}

# The name of an image file (relative to this directory) to place at the top of
# the title page.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_logo
#
#latex_logo = None
latex_logo = '{}/lpn.pdf'.format(path_images)

# If true, show page references after internal links. Default: False.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-latex_show_pagerefs
#
latex_show_pagerefs = True


# -- Options for HTML output -------------------------------------------------
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#options-for-html-output
#

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_theme
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_theme_path
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_theme_options
#
html_theme = 'sphinx_rtd_theme'

# A dictionary of values to pass into the template engine’s context for all
# pages. Single values can also be put in this dictionary using the -A
# command-line option of sphinx-build.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_context
#
html_context = {
    'document_title': title,
    'document_subtitle': subtitle,
    'document_number': docnumb,
    'document_revision': release,
    'document_vcs': identify,
}

#
# https://sphinx-rtd-theme.readthedocs.io/en/0.5.1/configuring.html
#
html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
    # Toc options
    'collapse_navigation': False,
    'sticky_navigation': True,
    'navigation_depth': 4,
    'includehidden': True,
    'titles_only': False
}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_title
#
html_title = u'{subtitle} {title}'.format(
    subtitle = subtitle,
    title = title,
)

# This value determines the text for the permalink; it defaults to "¶".
# Set it to None or the empty string to disable permalinks.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_add_permalinks
#
#html_add_permalinks = ""

# A shorter title for the navigation bar.  Default is the same as html_title.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_short_title
#
#html_short_title = None

# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_logo
#
html_logo = '{}/lpn.svg'.format(path_images)

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_favicon
#
html_favicon = '{}/lpn.ico'.format(path_images)

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_static_path
#
html_static_path = ['{}/html'.format(path_static)]

# A list of CSS files. The entry must be a filename string or a tuple
# containing the filename string and the attributes dictionary. The
# filename must be relative to the html_static_path, or a full URI
# with scheme. The attributes is used for attributes of <link> tag.
# It defaults to an empty list.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_css_files
#
html_css_files = [
    'fonts/DejaVu.css',
    'fonts/WenQuanYi.css',
    'css/force-dejavu.css',
#   'css/fix-cite.css',
#   'css/fix-float.css',
    'css/strikethrough.css',
    'css/underline.css',
    'css/tweaks-sphinx_rtd_theme.css',
]

# A list of JavaScript filename. The entry must be a filename string or
# a tuple containing the filename string and the attributes dictionary.
# The filename must be relative to the html_static_path, or a full URI
# with scheme. The attributes is used for attributes of <script> tag.
# It defaults to an empty list.
#
# https://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_js_files
#
#html_js_files = []

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_extra_path
#
html_extra_path = ['{}'.format(path_extra)]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_last_updated_fmt
#
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_use_smartypants
#
#html_use_smartypants =

# Custom sidebar templates, maps document names to template names.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_sidebars
#
#html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_additional_pages
#
#html_additional_pages = {}

# If false, no module index is generated.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_domain_indices
#
html_domain_indices = False

# If false, no index is generated.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_use_index
#
html_use_index = True

# If true, the index is split into individual pages for each letter.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_split_index
#
html_split_index = True

# If true, links to the reST sources are added to the pages.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_show_sourcelink
#
html_show_sourcelink = True

# Suffix to be appended to source links.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_sourcelink_suffix
#
html_sourcelink_suffix = '.txt'

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_show_sphinx
#
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_show_copyright
#
# html_show_copyright = tags.has('development')
html_show_copyright = True

# If true, license is shown in the HTML footer. Default is True.
html_show_license = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_use_opensearch
#
#html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_file_suffix
#
#html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_search_language
#
#html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_search_options
#
#html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
#
# http://www.sphinx-doc.org/en/3.x/usage/configuration.html#confval-html_search_scorer
#
html_search_scorer = '{}/js/scorer.js'.format(path_html_templates)


# -- Options for Reveal.js output --------------------------------------------
#
# https://sphinx-revealjs.readthedocs.io/en/v1.0.0/
#

# List of static files directory (same as html_static_path).
#
# https://sphinx-revealjs.readthedocs.io/en/v1.0.0/configurations.html#revealjs-static-path
#
revealjs_static_path = [
    '{}/revealjs'.format(path_static),
    '{}/html'.format(path_static),
]

# List of using fonts from Google Fonts (https://fonts.google.com/). If this
# value is set, render link and style tags into html.
#
# https://sphinx-revealjs.readthedocs.io/en/v1.0.0/configurations.html#revealjs-google-fonts
# 
revealjs_google_fonts = ['M PLUS 1p',]

# If you use revealjs_google_fonts, set last of font-family style.
#
# https://sphinx-revealjs.readthedocs.io/en/v1.0.0/configurations.html#revealjs-generic-font
revealjs_generic_font = 'sans-serif'

# Theme name of stylesheet for Reveal.js. If value does not have suffix .css,
# use bundled Reveal.js theme (included 'revealjs4/dist/theme').
# Examples: beige, black, blood, league, moon, night, serif, simple, sky,
#           solarized, white, custom.css
#
# https://sphinx-revealjs.readthedocs.io/en/v1.0.0/configurations.html#revealjs-style-theme
# https://revealjs.com/themes/
#
revealjs_style_theme = 'https://'  # disable, we use themeoverride to set the theme

# Raw JavaScript code for configuration of Reveal.js. If this value is set,
# render script tag after source script tags.
#
# https://sphinx-revealjs.readthedocs.io/en/v1.0.0/configurations.html#revealjs-script-conf
# https://revealjs.com/config/
# https://github.com/McShelby/reveal-themeoverride#configuration
# https://github.com/McShelby/reveal-altmode#configuration
# https://github.com/McShelby/reveal-pdfexport#configuration
# https://github.com/McShelby/reveal-helpbutton#configuration
# https://www.npmjs.com/package/reveal.js-menu#configuration
#
revealjs_script_conf = '''
    {
        dependencies: [
            {src: '_static/revealjs4/plugin/notes-pointer/notes-pointer.js', async: true},
        ],

        controls: true,
        progress: true,
        history: true,
        center: true,
        slideNumber: 'c/t',
        rollingLinks: true,
        previewLinks: true,
        hide_address_bar: true,
        view_distance: 3,

        margin: 0.01,
        minScale: 0.1,
        maxScale: 1.2,

        theme: 'black',
        fragments: true,

        transition: 'convex', // none/fade/slide/convex/concave/zoom
        background_transition: 'convex',

        helpButtonDisplay: 'first',

        altModeShortcut: 'A',

        altModeConfig: [
            {
                theme: 'white',
                fragments: true,
            },
            {
                theme: 'white',
                fragments: false,
            },
            {
                theme: 'black',
                fragments: false,
            },
        ],

        pdfExportShortcut: 'P',
        pdfSeparateFragments: false,

        menu: {
            openButton: true,
            keyboard: true,
            markers: true,
            numbers: true,
            themes: false,
            transitions: false,
        },

        notes_pointer: {
            pointer: {
                size: 24,
                color: 'rgba(255, 0, 0, 0.66)',
                key: 'R',
            },
            notes: {
                key: 'S',
            },
        },
    }
'''

# List of pulugin configurations. If this value is set, render script tag after
# source script tags. There are bundled Reveal.js plugins at 'revealjs4/plugin'.
#
# https://sphinx-revealjs.readthedocs.io/en/v1.0.0/configurations.html#revealjs-script-plugins
# https://revealjs.com/plugins/#built-in-plu
#
revealjs_script_plugins = [
    {
        'name': 'RevealHighlight',
        'src': 'revealjs4/plugin/highlight/highlight.js',
    },
    {
        'name': 'RevealMath',
        'src': 'revealjs4/plugin/math/math.js',
    },
#   {
#       'name': 'RevealNotes',
#       'src': 'revealjs4/plugin/notes/notes.js',
#   },
    {
        'name': 'RevealSearch',
        'src': 'revealjs4/plugin/search/search.js',
    },
    {
        'name': 'RevealZoom',
        'src': 'revealjs4/plugin/zoom/zoom.js',
    },
    # https://github.com/McShelby/reveal-themeoverride
    {
        'name': 'ThemeOverride',
        'src': 'revealjs4/plugin/themeoverride/themeoverride.js',
    },
    # https://github.com/McShelby/reveal-altmode
    {
        'name': 'AltMode',
        'src': 'revealjs4/plugin/altmode/altmode.js',
    },
    # https://github.com/McShelby/reveal-pdfexport
    {
        'name': 'PdfExport',
        'src': 'revealjs4/plugin/pdfexport/pdfexport.js',
    },
    # https://github.com/McShelby/reveal-helpbutton
    {
        'name': 'HelpButton',
        'src': 'revealjs4/plugin/helpbutton/helpbutton.js',
    },
    # https://www.npmjs.com/package/reveal.js-menu
    {
        'name': 'RevealMenu',
        'src': 'revealjs4/plugin/menu/menu.js',
    },
]

# List of sources that render as script tags. There is bundled Reveal.js script at
# 'revealjs4/dist/reveal.js'. Example: ["presentation.js"]
#
# https://sphinx-revealjs.readthedocs.io/en/v1.0.0/configurations.html#revealjs-script-files
#
# revealjs_script_files = []

# List of using custom css (same of html_css_files). If you want to customize
# presentation by CSS, write external css and use it.
#
# https://sphinx-revealjs.readthedocs.io/en/v1.0.0/configurations.html#revealjs-css-files
#
revealjs_css_files = [
    'css/underline.css',
    'css/strikethrough.css',
    'css/tweaks-revealjs.css',
    'revealjs4/plugin/highlight/zenburn.css',
    'revealjs4/dist/theme/black.css\" id=\"theme',  # QnD hack for themeoverride
]


# -- Sphinx Monkey Patches ---------------------------------------------------

# Avoid runtime errors with the Reveal.js builder in case of the
# LaTeX builder. Errors were:
#
#     Exception occurred:
#       File ".../sphinx/writers/latex.py", line 2044, in unknown_visit
#         raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
#     NotImplementedError: Unknown node: revealjs_section
#     NotImplementedError: Unknown node: revealjs_break
#     NotImplementedError: Unknown node: revealjs_slide
#     NotImplementedError: Unknown node: revealjs_fragments

def setup(app: sphinx.application.Sphinx):
    app.add_node(
        sphinx_revealjs.nodes.revealjs_section, override=True,
        html=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write),
        revealjs=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write),
        latex=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write)
    )
    app.add_node(
        sphinx_revealjs.nodes.revealjs_break, override=True,
        html=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write),
        revealjs=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write),
        latex=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write)
    )
    app.add_node(
        sphinx_revealjs.nodes.revealjs_slide, override=True,
        html=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write),
        revealjs=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write),
        latex=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write)
    )
    app.add_node(
        sphinx_revealjs.nodes.revealjs_fragments, override=True,
        html=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write),
        revealjs=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write),
        latex=(sphinx_revealjs.writers.not_write, sphinx_revealjs.writers.not_write)
    )
